//
// Created by Finst on 12/12/2018.
//

#ifndef ALGORITHMS_DATA_STRUCTURES_MAZEGENERATOR_H
#define ALGORITHMS_DATA_STRUCTURES_MAZEGENERATOR_H


class MazeGenerator {

};


#endif //ALGORITHMS_DATA_STRUCTURES_MAZEGENERATOR_H
